version: '3.8'

services:

  mysql:
    image: mysql:8.0.22
    container_name: mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_testect
      MYSQL_TCP_PORT: 3307